# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69aab4332ca3d1c8445cd1dcf759064bc4ecee70187fc555801142cfd643c695c31af836d606bd84dec4b8b2bef9fb2d389762298bc0d56cdb784c3ed11dee65

test:
  secret_key_base: a926c437464a8b76fb08c2eacc8d60aed85df0ba66a317448e2a9a8cc52ad04f84c4ce8e2ea672e2316494b9cd2d5b2b8a6b2f1b8f92b0aa9c9845f710d3b765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
